ZERO, 
TEMP,
CLASS_SPECIFIER,//decl_specifier_seq.cpp -start
CONSTANT_EXPRESSION,
EXPRESSION,
SIMPLE_TEMPLATE_ID,
TYPE_SPECIFIER_SEQ,
CLASS_NAME,
TYPEDEF_NAME,
ENUM_NAME,
NAMESPACE_ALIAS,
ORIGINAL_NAMESPACE_NAME,
TYPENAME_SPECIFIER,

